### ISSUE TITLE
During reconnections, resolve_hostname() should wait for 'listener' thread to terminate before creating a new socket

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux#49]
M2MConnectionHandlerPimpl::resolve_hostname() has the following code to close a socket during reconnections:

```
    if(_socket_server > 0) {
        close(_socket_server);
        _socket_server = -1;
        /* Should wait here */
    }
    create_socket();

```

Sometimes, during a retry/reconnection attempt, the newly created socket has exactly the same fd as the old one, leading to unexpected behavior in the 'listener' thread running data_receive(), which calls _security_impl->read(). The latter may never return.

The code should wait for the 'listener' thread to terminate (using pthread_join() or similar) after closing the socket and before calling create_socket(). Or alternatively find some other way to terminate the 'listener' thread more gracefully before closing the socket via close().

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-850

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
