### ISSUE TITLE
mbed-client-linux-example is unavailable

### ISSUE THREAD

**Issue by viktorkho** [ARMmbed/mbed-client-linux#66]
There are a lot of links to https://github.com/ARMmbed/mbed-client-linux-example.git, but this page is 404.
Can you please fix this issue? Thanks/

**Comment by ghost** [comment]
still broken.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
